"""create model_configs table

Revision ID: 4b99014dbbf0
Revises: 4bc81a608c86
Create Date: 2026-09-21 11:41:45.730999+00:00

"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4b99014dbbf0'
down_revision: str | None = '4bc81a608c86'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """应用本次迁移。"""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('model_configs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('llm_provider', sa.String(length=32), server_default=sa.text("'deepseek'"), nullable=False),
    sa.Column('llm_api_key_encrypted', sa.Text(), nullable=True),
    sa.Column('llm_base_url', sa.String(length=255), nullable=True),
    sa.Column('llm_model', sa.String(length=128), server_default=sa.text("'deepseek-chat'"), nullable=False),
    sa.Column('llm_temperature', sa.Float(), server_default=sa.text('0.1'), nullable=False),
    sa.Column('llm_max_tokens', sa.Integer(), server_default=sa.text('2048'), nullable=False),
    sa.Column('embed_provider', sa.String(length=32), server_default=sa.text("'local'"), nullable=False),
    sa.Column('embed_api_key_encrypted', sa.Text(), nullable=True),
    sa.Column('embed_model', sa.String(length=128), server_default=sa.text("'BAAI/bge-m3'"), nullable=False),
    sa.Column('embed_model_path', sa.Text(), nullable=True),
    sa.Column('embed_dimension', sa.Integer(), server_default=sa.text('1024'), nullable=False),
    sa.Column('rerank_provider', sa.String(length=32), server_default=sa.text("'local'"), nullable=False),
    sa.Column('rerank_api_key_encrypted', sa.Text(), nullable=True),
    sa.Column('rerank_model', sa.String(length=128), server_default=sa.text("'bge-reranker-large'"), nullable=False),
    sa.Column('rerank_model_path', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """回滚本次迁移。

    必须提供可用的回滚实现而不是留空：留空会让 `alembic downgrade` 静默成功
    但数据库结构实际未变，之后再次 upgrade 会因对象已存在而失败。
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('model_configs')
    # ### end Alembic commands ###
