"""create documents ingestion_tasks and knowledge_base_indexes

Revision ID: 305a870c9fd7
Revises: 4b99014dbbf0
Create Date: 2026-09-21 12:14:47.129010+00:00

"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '305a870c9fd7'
down_revision: str | None = '4b99014dbbf0'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """应用本次迁移。"""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('documents',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('stored_path', sa.Text(), nullable=False),
    sa.Column('content_type', sa.String(length=128), nullable=True),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), server_default='uploaded', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_documents_user_sha256', 'documents', ['user_id', 'sha256'], unique=False)
    op.create_index('ix_documents_user_status', 'documents', ['user_id', 'status'], unique=False)
    op.create_table('knowledge_base_indexes',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('collection_name', sa.String(length=128), nullable=False),
    sa.Column('embedding_provider', sa.String(length=32), nullable=False),
    sa.Column('embedding_model', sa.String(length=128), nullable=False),
    sa.Column('embedding_dimension', sa.Integer(), nullable=False),
    sa.Column('embedding_signature', sa.String(length=512), nullable=False),
    sa.Column('chunk_size', sa.Integer(), nullable=False),
    sa.Column('chunk_overlap', sa.Integer(), nullable=False),
    sa.Column('index_version', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), server_default='building', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_kb_indexes_collection', 'knowledge_base_indexes', ['collection_name'], unique=True)
    op.create_index('ix_kb_indexes_user_status', 'knowledge_base_indexes', ['user_id', 'status'], unique=False)
    op.create_table('ingestion_tasks',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('task_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('document_id', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.String(length=32), server_default='pending', nullable=False),
    sa.Column('progress', sa.Integer(), server_default='0', nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_ingestion_tasks_task_id', 'ingestion_tasks', ['task_id'], unique=True)
    op.create_index('ix_ingestion_tasks_user_status', 'ingestion_tasks', ['user_id', 'status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """回滚本次迁移。

    必须提供可用的回滚实现而不是留空：留空会让 `alembic downgrade` 静默成功
    但数据库结构实际未变，之后再次 upgrade 会因对象已存在而失败。
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_ingestion_tasks_user_status', table_name='ingestion_tasks')
    op.drop_index('ix_ingestion_tasks_task_id', table_name='ingestion_tasks')
    op.drop_table('ingestion_tasks')
    op.drop_index('ix_kb_indexes_user_status', table_name='knowledge_base_indexes')
    op.drop_index('ix_kb_indexes_collection', table_name='knowledge_base_indexes')
    op.drop_table('knowledge_base_indexes')
    op.drop_index('ix_documents_user_status', table_name='documents')
    op.drop_index('ix_documents_user_sha256', table_name='documents')
    op.drop_table('documents')
    # ### end Alembic commands ###
