"""create conversations and messages

Revision ID: 22a19e3642c9
Revises: 305a870c9fd7
Create Date: 2026-09-21 12:24:22.250238+00:00

"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '22a19e3642c9'
down_revision: str | None = '305a870c9fd7'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """应用本次迁移。"""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversations',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('conversation_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('title', sa.String(length=255), server_default='新会话', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_conversations_user_conv', 'conversations', ['user_id', 'conversation_id'], unique=True)
    op.create_table('messages',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('conversation_id', sa.String(length=36), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('source_entries', sa.JSON(), nullable=True),
    sa.Column('trace_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_messages_user_conv_created', 'messages', ['user_id', 'conversation_id', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """回滚本次迁移。

    必须提供可用的回滚实现而不是留空：留空会让 `alembic downgrade` 静默成功
    但数据库结构实际未变，之后再次 upgrade 会因对象已存在而失败。
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_messages_user_conv_created', table_name='messages')
    op.drop_table('messages')
    op.drop_index('ix_conversations_user_conv', table_name='conversations')
    op.drop_table('conversations')
    # ### end Alembic commands ###
